"""initial

Revision ID: 08907ac61fa1
Revises: 
Create Date: 2019-12-06 20:53:45.156321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08907ac61fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventAssociationType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['EventAssociationType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['EventType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IntervalType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['IntervalType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemAssociationType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['ItemAssociationType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemEventType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['ItemEventType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['ItemType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventAspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventAssociation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('event_1_id', sa.Integer(), nullable=True),
    sa.Column('event_2_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['event_1_id'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['event_2_id'], ['Event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventTypeInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['EventType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_count', sa.Integer(), nullable=True),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['IntervalType.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['Universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemAspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemAssociation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('item_1_id', sa.Integer(), nullable=True),
    sa.Column('item_2_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['item_1_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['item_2_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemTypeInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ItemType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CalendarInterval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['Calendar.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['Interval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventAspectDetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('event_aspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_aspect_id'], ['EventAspect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventAssociationTypeInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_association_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_association_id'], ['EventAssociation.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['EventAssociationType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemAspectDetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.Column('edited_on', sa.Date(), nullable=True),
    sa.Column('item_aspect_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['Creator.id'], ),
    sa.ForeignKeyConstraint(['item_aspect_id'], ['ItemAspect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemAssociationTypeInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_association_id', sa.Integer(), nullable=True),
    sa.Column('item_association_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_association_id'], ['ItemAssociation.id'], ),
    sa.ForeignKeyConstraint(['item_association_type_id'], ['ItemAssociationType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ItemEventTypeInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_event_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_event_id'], ['ItemEvent.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ItemEventType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemEventTypeInventory')
    op.drop_table('ItemAssociationTypeInventory')
    op.drop_table('ItemAspectDetail')
    op.drop_table('EventAssociationTypeInventory')
    op.drop_table('EventAspectDetail')
    op.drop_table('CalendarInterval')
    op.drop_table('ItemTypeInventory')
    op.drop_table('ItemEvent')
    op.drop_table('ItemAssociation')
    op.drop_table('ItemAspect')
    op.drop_table('Interval')
    op.drop_table('EventTypeInventory')
    op.drop_table('EventAssociation')
    op.drop_table('EventAspect')
    op.drop_table('ItemType')
    op.drop_table('ItemEventType')
    op.drop_table('ItemAssociationType')
    op.drop_table('Item')
    op.drop_table('IntervalType')
    op.drop_table('EventType')
    op.drop_table('EventAssociationType')
    op.drop_table('Event')
    op.drop_table('Calendar')
    op.drop_table('Universe')
    op.drop_table('Creator')
    # ### end Alembic commands ###
